name       : libgeocode-glib2
version    : 3.26.4
release    : 2
source     :
    - https://download.gnome.org/sources/geocode-glib/3.26/geocode-glib-3.26.4.tar.xz : 2d9a6826d158470449a173871221596da0f83ebdcff98b90c7049089056a37aa
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : 
    - Geocoding library
    - ^libgeocode-glib-common : Shared component for libgeocode-glib 1 and 2
description: |
    geocode-glib is a convenience library for the geocoding (finding longitude, and latitude from an address) and reverse geocoding (finding an address fromcoordinates). It uses Nominatim service to achieve that. It also caches (reverse-)geocoding requests for faster results and to avoid unnecessary server load.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-3.0)
    - gtk-doc
rundeps    :
    - libgeocode-glib-common
patterns   :
    - ^libgeocode-glib-common :
        - /usr/share/icons/hicolor/scalable/places/poi-*.svg
setup      : |
    %meson_configure -Denable-installed-tests=false -Dsoup2=false
build      : |
    %ninja_build
install    : |
    %ninja_install
